all :
	@echo "\033[33mWarning: This test is under sudo, do not run it on your device.\033[0m"
	@echo "\033[33mYou have 5 seconds to press Ctrl+C to cancel.\033[0m"
	@sleep 5
	@cc -o test-root test-root.c
	@sudo ./test-root