.\" I hope it works...
.TH "RURI" "1" "August 2023" "RURI v2\&.0" "RURI MANUAL"
.SH "NAME"
ruri \- Lightweight, User\-friendly Linux-container Implementation\&.
.SH "SYNOPSIS"
.sp
.nf
.B ruri \fB\,OPTIONS\fR
.B ruri [\fB\,ARGS\fR] \fB\,CONTAINER_DIRECTORY\fR [\fB\,INIT_COMMAND\fR]
.fi
.sp
.SH "DESCRIPTION"
.sp
ruri is the romaji acronym of Lightweight, User-friendly Linux\-container Implementation\&.
.TP
It is designed to provide better security for Linux containers on devices that do not support docker\&.    
.TP
PS: ruri is pronounced as \fB\,\m[cyan]/luli/\m[]\fR , or you can just call it \fB\,\m[cyan]瑠璃\m[]\fR in Chinese or Japanese as well.
.TP
See \m[blue]\fB\,https://github.com/Moe-hacker/ruri\m[]\fR for source code.
.sp
.SH "OPTIONS"
.PP
\-v, \-\-version
.RS 4
Print the version info\&.
.SH "EXAMPLES"
.sp
Quickly setup a container(with rootfstool):
.PP
  git clone https://github.com/Moe-hacker/rootfstool
  cd rootfstool
  ./rootfstool download -d alpine -v edge
  mkdir /tmp/alpine
  sudo tar -xvf rootfs.tar.xz -C /tmp/alpine
.sp
\fB\,Run chroot container:\fR
.PP
  sudo ruri /tmp/alpine
.sp
\fB\,Very simple as you can see.\fR
.sp
Run privileged chroot container:
.PP
  sudo ruri -p /tmp/alpine
.sp
But if you want to make the container more secure:
.PP
  sudo ruri -d /tmp/alpine
.sp
If you want to run privileged chroot container,
but you don't want to give the container cap_sys_chroot privileges:
.PP
  sudo ruri -p --drop cap_sys_chroot /tmp/alpine
.sp
If you want to run chroot container with common privileges,
but you want cap_sys_admin to be kept:
.PP
  sudo ruri --keep cap_sys_admin /tmp/alpine
.sp
\fB\,About unshare:\fR
.sp
Unshare container's capability options are same with chroot.
.sp
But it's recommended to start rurid before running unshare containers:
.PP
  sudo ruri -D
.sp
Run unshare container:
.PP
  sudo ruri -u /tmp/alpine
.sp
List running containers:
.PP
  sudo ruri -l
.sp
Umount the container:
.PP
  sudo ruri -U /tmp/alpine
.sp
Finally, kill the daemon:
.PP
  sudo ruri -K
.SH "COPYRIGHT"
Copyright \(co 2022-2023 Moe-hacker.
.sp
License: MIT <https://mit-license.org>.
.SH "CONTACT"
.sp
Author: \fB\,\m[cyan]Moe Hacker\m[]\fR
.sp
Github: \fB\,\m[cyan]@Moe-hacker\m[]\fR
.sp
For any bugs, please report at \m[blue]\fB\,https://github.com/Moe-hacker/ruri/issues\m[]\fR